---
- name: Download {{ cwa_agent }} file
  get_url:
    url: "{{ CWA_URL }}"
    dest: /tmp/
  tags:
    - download
- name: Installing the Cloudwatch RPM ...
  yum:
    name: /tmp/amazon-cloudwatch-agent.rpm
    state: present
  tags: install_rpm_package
- name: Download {{ config_json }} file
  get_url:
    url: "{{ config_json }}"
    dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
  tags:
    - download config file
- name: Starting the cloudwatch service
  command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a
    fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json
    -s
  tags: start_service
- Name: enable cloudwatch cwa_agent
  systemd:
    name: amazon-cloudwatch-agent
    enable: yes
- name: Deleting the cloudwatch RPMvfile ...
  file:
    path: /tmp/amazon-cloudwatch-agent.rpm
    state: absent
  tags: delete_rpm_package
